### ISSUE TITLE
Invalid - Incorrect Password Prompt

### ISSUE THREAD

**Issue by jordanpaquin** [GKhankles/move-thrower#10]
**Summary:**
The message displayed after entering an incorrect password is unclear and potentially confusing to users.  
**Description:** 
The message displayed to users after entering an incorrect password is unclear. 
"The password is invalid or the user does not have a password.”
The first part is fine, but the "or the user does not have a password” is unclear and potentially confusing to users as it’s not a common error message that they’d see on other websites.
**Severity:**
Trivial

**Comment by zzheng26** [comment]
Changed the prompt to be much clearer.
