### ISSUE TITLE
Needs Implementing - Load and Saving Pokemon

### ISSUE THREAD

**Issue by jordanpaquin** [GKhankles/move-thrower#11]
**Summary:**
The functionality to Load and Save Pokemon for each user still has to be implemented.
**Description:** 
It’s nice that the load and save feature only is displayed after a user logs in. It’s just got to be implemented, and let the user be able to edit the name field before saving.  
**Severity:**
Critical

**Comment by zzheng26** [comment]
The textbox is lacking a "onChange" statement and this issue is fixed.
