### ISSUE TITLE
Bug - Calculate Recommended Move shows wrong moves after switching Pokemon

### ISSUE THREAD

**Issue by jordanpaquin** [GKhankles/move-thrower#12]
**Summary:**
After switching Pokemon from attacking to defending the Recommend Moves are displayed for the defending Pokemon
**Description:** 
When a "Switch Roles" is clicked, the Recommend Moves displayed are still listed incorrectly as the attacking moves of the Pokemon that's not defending.
For example, having Charmander attack Bulbasaur and then clicking "Switch Roles" displays the attack moves for Charmander even though he's now defending. And Bulbasaur's recommended attack moves are not displayed. 
**Severity:**
Blocking

**Comment by jjhanson3** [comment]
Now can properly calculate moves after the pokemon switch places. The user will have to click the calculate button to recalculate moves, but that is intended.
