### ISSUE TITLE
Bug - Calculate Move Thrower Doesn’t Show Moves

### ISSUE THREAD

**Issue by jordanpaquin** [GKhankles/move-thrower#3]
**Summary:**
Having Melmetal attack and Blastoise defend with Generation 7 selected doesn’t show a list of recommended moves
**Description:** 
Having Melmetal attack and Blastoise defend with Generation 7 selected doesn’t show a list of recommended moves
**Severity:**
Critical

**Comment by jjhanson3** [comment]
Meltan and Melmetal didn't have legitimate moves in Generation 7 (Only in Pokemon GO), so they've been removed from the Generation 7 file. Still will calculate in Generation 8 once that generation has been implemented.
