### ISSUE TITLE
Invalid - Changing Generations Displays Name, Picture, and Stats of Different Pokemon

### ISSUE THREAD

**Issue by jordanpaquin** [GKhankles/move-thrower#4]
**Summary:**
Changing generations displays the stats and picture of the previously selected Pokemon, but the name of the new generation’s default; this could be confusing to users who don’t immediately select a new Pokemon. 
**Description:** 
Changing from a higher generation to a lower generation where the Pokemon you had selected didn’t yet exist changes the default name to Bulbasaur but keeps the stats and the photo of the previously selected Pokemon.  This could be potentially confusing to users and it would be better to have it switch to a default (select new Pokemon) from the drop down menu with the stat fields being cleared.
For instance selecting Melmetal from Generation 7, then switching back to Generation 3 displays Bulbasaur’s name with Melmetal’s Picture and Stats. 
**Severity:**
Trivial

**Comment by jjhanson3** [comment]
Now sets to Bulbasaur as a default whenever the user changes generations
