### ISSUE TITLE
Bug - Missing Picture for Multiple Pokemon

### ISSUE THREAD

**Issue by jordanpaquin** [GKhankles/move-thrower#6]
**Summary:**
The Pokemon picture is missing for the Pokemon listed in the description
**Description:** 
Oricorio baile Style
Lycanroc Midday Form
Wishiwashi Solo Form
Minior Meteor Form
Darmanitan
Basculin
Giratina
Shaymin Land Forme
Wormadam Plant Cloak
Deoxys Normal Forme
**Severity:**
Critical

**Comment by jjhanson3** [comment]
Fixed, changed how we sent information to PokeAPI. Started sending the Pokemon IDs instead of their names
