### ISSUE TITLE
Invalid - Radial Buttons for Generation Selection

### ISSUE THREAD

**Issue by jordanpaquin** [GKhankles/move-thrower#7]
**Summary:**
The radial buttons should be aligned so that the numbers are all next to the button choice they represent. 
**Description:** 
Currently the number “6” is on the lower line of radial buttons, while it’s actual radial button is on the upper line. 
**Severity:**
Trivial

**Comment by jjhanson3** [comment]
Fixed spacing of radial buttons by grouping the inputs up with divs
